name       : tilp
version    : 1.18
release    : 2
source     :
    - https://downloads.sourceforge.net/project/tilp/tilp2-linux/tilp2-1.18/tilp2-1.18.tar.bz2 : 7b3ab363eeb52504d6ef5811c5d264f8016060bb7bd427be5a064c2ed7384e47
license    : GPL-2.0-or-later
component  : office
summary    : TI Linking Program
description: |
    Software for communicating with calculators from Texas Instruments.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(ticalcs2)
    - intltool
setup      : |
    %patch -p1 < $pkgfiles/remove-kde.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
